apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: "<YOUR-API-KEY>"
    appKey: "<YOUR-APP-KEY>"
  agent:
    env:
      - name: DD_KUBELET_TLS_VERIFY
        value: "false"
      - name: DD_DOGSTATSD_TAG_CARDINALITY
        value: "high"
    image: 
      name: "datadog/agent:latest"
    apm:
      enabled: true
    process:
      enabled: true
    log:
      enabled: true
      logsConfigContainerCollectAll: true
    security:
      compliance:
        enabled: true
      runtime:
        enabled: false
    systemProbe:
      enabled: true
      bpfDebugEnabled: true
  clusterAgent:
    image: 
      name: "datadog/cluster-agent:latest"
    config:
      clusterChecksEnabled: true
      externalMetrics:
        enabled: true
      admissionController:
        enabled: true
