apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: "<YOUR-API-KEY>"
    appKey: "<YOUR-APP-KEY>"
  agent:
    config:
      leaderElection: true
      collectEvents: true
      criSocket:
        criSocketPath: /var/run/crio/crio.sock
        useCriSocketVolume: true
    env:
      - name: DD_KUBELET_TLS_VERIFY
        value: "false"
      - name: DD_DOGSTATSD_TAG_CARDINALITY
        value: "orchestrator"
      - name: DD_EXTRA_CONFIG_PROVIDERS
        value: "endpointschecks clusterchecks"
    image: 
      name: "datadog/agent:latest"
    apm:
      enabled: true
    process:
      enabled: true
    log:
      enabled: true
      logsConfigContainerCollectAll: true
    security:
      compliance:
        enabled: true
      runtime:
        enabled: false
    systemProbe:
      enabled: true
      bpfDebugEnabled: true
  clusterAgent:
    image: 
      name: "datadog/cluster-agent:latest"
    config:
      env:
      - name: DD_EXTRA_CONFIG_PROVIDERS
        value: "kube_endpoints kube_services"
      - name: DD_COLLECT_KUBERNETES_EVENTS
        value: "true"
      - name: DD_LEADER_ELECTION
        value: "true"
      clusterChecksEnabled: true
      externalMetrics:
        enabled: true
      admissionController:
        enabled: true
